language: ruby
rvm:
    - "2.0.0"
install:
    - "gem install sass"
    - "gem install bourbon"
    - "gem install neat"
    - "npm install -g grunt-cli"
    - "npm install -g bower"
    - "npm install"
    - "bower install"
script:
    - "grunt build"
branches:
    only:
        - "develop"