language: node_js
node_js:
- '0.10'
install:
- gem install sass
- gem install bourbon
- gem install neat
- npm install -g grunt-cli
- npm install -g bower
- npm install
- bower install
script:
- grunt build
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id:
    secure: CCzAUpeLvxsCB3hj2SVhP5ERNLSqWp2qHK2tlv8e+rtlHFvgtqKPSlr3tXX942UBrUHpbXdkr5xvRbPSb5fUXHxwtVyHhvujlLxNvX9fwLyHQb7oEIZBDkoOlrHJuIIhO32oNuReSiORjrFMjn5llj82/MPxK2/wT8XZEPpBHcA=
  secret_access_key:
    secure: PdmZbWSfi8xMFdDMCq0+EOtEJBMGKi19z26SwsPGL+Mhnwf3cLY8i7UyrdS9WsuD/0WYkzlG+2QW+LQETYoCXTuN8IfqXz1qMwjgZQoCTmVE5fghERkAoSvM4wa2uZHcXZFg1A8ECiSDsjlV0za3T+rjIeHleceTGGnjG2AGcRY=
  bucket: kopijunkie.me
  skip_cleanup: true
  endpoint: kopijunkie.me.s3-website-eu-west-1.amazonaws.com/
  region: eu-west-1
  local-dir: dist
