language: node_js
node_js:
- '0.10'
install:
- gem install sass
- gem install bourbon
- gem install neat
- npm install -g grunt-cli
- npm install -g bower
- npm install
- bower install
script:
- grunt build
branches:
  only:
  - master
deploy:
  provider: s3
  bucket: kopijunkie.me
  skip_cleanup: true
  endpoint: kopijunkie.me.s3-website-eu-west-1.amazonaws.com/
  region: eu-west-1
  local-dir: dist
env:
  global:
  - secure: g5L3wnXTe7G/ZikoXL71/kLb98Q/P193+3/SRBbsDNkOmlN9JflsZuvdRQ+NH4pTQjtmW8kHgEXpafT2xNch+tC4OnbBPX8+17ZT5zB+QRw5AWN82crBaZQDZMuTn7ffMl8fmlh4+elRxKXNxkkBMvXL/okLFfT0+n3VEQj8BDc=
  - secure: GsNfaK3oaMDq5WeRZnmWyt5f+tKDAGZzkd2RG1N34piwBLS3D5iImOTLzhuDjeRTge873kgjXi4G+QKdYQIgKBO588h65YRIWvoRKITuHl4oyocfKS8CrvpGfQAvC1Te7L1imvCoMiLKRXS/KkkDdjJB7raSu9owE8cxo1EMGe4=
